### ISSUE TITLE
Въпроси по втора част на домашното с картите

### ISSUE THREAD

**Issue by kall0m** [elsys/oop2017-2018#17]
1. Може ли да променяме неща от първата част на домашното, които сме пратили вече?

2. Може ли да добавяме методи в класовете, имплементиращи интерфейсите?

3. В метода public void process(String command) в интерфейса Game трябва да намерим подадената прочетена операция чрез command в списъка от операции и да я изпълним ако я има (подобно на задачата от първия срок)? Съответно може ли да правим наследници на класа, който имплементира интерфейса Operation за двата вида операции? В този случай методът execute може ли да го променим да е абстрактен?

4. Когато програмата изписва съобщение за грешка, трябва ли да направим още класове, подобни на CardException и да се хвърлят те, или може само да се принтира съобщението?

5. AbstractGameTest трябва ли да има наследници, защото липсват?

**Comment by wencakisa** [comment]
По повод `testDeal()` в `AbstractGameTest.java`:

```java
    // ...
    game.process("deal");
    // Тук се deal-ват карти от тестето
    // deck.deal() връща инстанция на Hand, в която се пазят картите от последно изтеглената ръка
    // a.k.a game.getDealtHand()
    assertNotNull(game.getDealtHand());
    assertEquals(deckSize() - handSize(), game.getDeck().size());
    List<Card> cards = game.getDealtHand().getCards();
    // Взимаме картите от изтеглената ръка
    // Да кажем, че играем белот
    // Изтеглената ръка ако са сортирани картите изглежда по този начин
    // [C7, C8, C9, C10, CJ, CQ, CK, CA]

    // Но след като вече сме изтеглили карти, в clearDeck тях ги няма и няма как да сравним
    // clearDeck.subList(0, handSize()) с cards
    // В clearDeck вече липсват последните карти, защото са изтеглени
    assertEquals(clearDeck.subList(0, handSize()), cards);
```

**Comment by denishristov** [comment]
Ако подаваш копие на cards когато правиш deck в gamefactory, а не самия пойнтер минава теста

**Comment by egotsev** [comment]
не, това трябва да става в статичните методи на factory класа.

**Comment by kall0m** [comment]
В класа, който имплементира интерфейса Operation (например AbstractOperation) имам променлива от тип Game, която е protected и е достъпна за наследниците-операции - War, Belote, Size, Deal и т.н. Проблем ли е ако тази променлива от тип Game е **статична**, тъй като ако не е, то за всяка друга операция в йерархията, промените, направени от другите операции върху game-а, не се отразяват?
(Например когато напиша "War" се създава War game с подадените карти, но после ако напиша "size" ми казва "No deck", тъй като War game-а се е създал, но в операцията Size този _game_ не е с картите за War game от подадената команда преди това, а си е с първоначално въведените карти.)

**Comment by egotsev** [comment]
Не проблем, ами направо е глупост.
