### ISSUE TITLE
ToDo List Homework - Task equality

### ISSUE THREAD

**Issue by wencakisa** [elsys/oop2017-2018#20]
Считаме ли че две инстанции на `Task` са *равни*, само чрез използването на вече дефиниран `equals()` метод в имплементацията?

Например тези две задачи водят ли се различни:

> ***TODO*    | Do OOP homework              | Low    | school, programming**
> ***DONE*    | Do OOP homework              | Low    | school, programming**

след като само `status` атрибутът им е различен?

**Comment by egotsev** [comment]
Разбира се, две задачи са равни тогава, когато `equals` връща `true`. Относно двете задачи - приемете, че са различни.
